# -*- coding: utf-8 -*-
"""lab_02_4_before.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BTFllwcb56A0jRh6enTZOfM3hjxkKPvF
"""

import numpy as np # математические операции
import pandas as pd # операции с табличками
import statsmodels.formula.api as smf # модели 
from sklearn.linear_model import LinearRegression # линейная регрессия без статистики
import seaborn as sns # графики
import matplotlib.pyplot as plt # графики

!pip install rdatasets # наборы данных
from rdatasets import data

!pwd

!ls

!cd sample_data

!cd ..

flats = pd.read_csv('flats_moscow.txt')

flats.head()

flats = pd.read_csv('flats_moscow.txt', sep='\t')
flats.head()

flats.describe().transpose()

sns.relplot(data=flats, x='totsp', y='price')

sns.relplot(data=flats, x='totsp', y='price')
plt.xlabel('Общая площадь квартиры (м2)')
plt.ylabel('Цена (тыс. уе.)')
plt.title('Стоимость двухкомнатных квартир в Москве в 2001 г.');

mod_1 = smf.ols('price ~ totsp', data=flats)
fit_1 = mod_1.fit()
fit_1.summary()

flats['othersp'] = flats['totsp'] - flats['livesp'] - flats['kitsp']

mod_2 = smf.ols('price ~ livesp + kitsp + othersp', data=flats)
fit_2 = mod_2.fit()
fit_2.summary()

from statsmodels.iolib.summary2 import summary_col

summary_col([fit_1, fit_2])

summary_col([fit_1, fit_2], stars=True)

fit_1.nobs

fit_1.rsquared

'{:.0f}'.format(fit_1.nobs)

'{:.2f}'.format(fit_1.rsquared)

more_info = {'obs': lambda x: '{:.0f}'.format(x.nobs), 
             'r-squared': lambda x: '{:.2f}'.format(x.rsquared)}

summary_col([fit_1, fit_2], stars=True, info_dict=more_info)

results = summary_col([fit_1, fit_2], stars=True, info_dict=more_info)

results.as_latex()

