# -*- coding: utf-8 -*-
"""lab_02_2_before.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dtRKzAQZ5hNIJAEB2bgzyPZLR_lSpjPV
"""

import numpy as np # математические операции
import pandas as pd # операции с табличками
import statsmodels.formula.api as smf # модели 
from sklearn.linear_model import LinearRegression # линейная регрессия без статистики
import seaborn as sns # графики
import matplotlib.pyplot as plt # графики

!pip install rdatasets # наборы данных
from rdatasets import data

swiss = data('swiss')

swiss.head()

model = smf.ols('Fertility ~ Agriculture + Education + Catholic', data=swiss)
fit = model.fit()

fit.summary()

fit.summary(alpha=0.01)

fit.conf_int(alpha=0.01)

fit.tvalues

fit.pvalues

fit_summary = fit.summary()

fit_summary.as_latex()

coef_info = pd.DataFrame(fit_summary.tables[1].data)
coef_info

coef_info = coef_info.drop(0)

coef_info.columns = ['coef', 'value', 'std', 't_stat', 'p_value', 'left_ci', 'right_ci']

coef_info

hypo = 'Agriculture = Education, Catholic = 0'

fit.t_test(hypo)

fit.f_test(hypo)

