---
title: "Нано презентация"
subtitle: "⚔<br/>с помощью xaringan"
author: "Винни-Пух"
date: "Сегодня!"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---


```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
library(skimr) # описательные статистики (вместо psych в видеолекциях)
library(lmtest) # тестирование гипотез в линейных моделях
library(rio) # загрузка данных в разных форматах (вместо foreign в видеолекциях)
library(vcd) # мозаичные графики
library(hexbin) # двумерный график с шестиугольниками
library(sjPlot) # визуализация результатов регрессии
library(tidyverse) # графики и манипуляции с данными, подключаются пакеты dplyr, ggplot2, etc
library(tidymodels) # удобства для манипуляций с моделями
library(huxtable) # несколько таблиц вместе
library(knitr) # Rmd
opts_chunk$set(echo = FALSE, message = FALSE)
```

## Нано исследование цен на квартиры :)

```{r load}
f = import('flats_moscow.txt')
f = mutate_at(f, vars(walk, brick, floor, code), factor)
```

В нашем наборе данных `r nrow(f)` квартир.
Средняя стоимость квартиры `r round(mean(f$price), 0)` тыс. долларов.

---

### Построим график

```{r}
qplot(data = f, x = log(totsp),
      y = log(price)) +
  labs(x = 'Логарифм общей площади квартиры (м2)',
       y = 'Логарифм цены квартиры (тыс. долл.)',
       title = 'Соотношение цены и площади квартиры в Москве')
```

---

## Оценим простенькую модель и ещё две :)

$$\ln price_i = \beta_1 + \beta_2 \ln totsp_i + u_i$$


---

## Результаты оценивания

```{r, results='asis', warning=FALSE}
m1 = lm(data = f, log(price) ~ log(totsp))
m2 = lm(data = f, log(price) ~ log(totsp) + brick)
m3 = lm(data = f,
        log(price) ~ log(totsp) + brick +
                        brick:log(totsp))

reg_table = huxreg(m1, m2, m3)
print_html(reg_table)
```


